version: "3.7"

networks:
  backend:
    external:
      name: my-network

volumes:
  redis_data:
    driver: local

services:
  server:
    hostname: server
    build:
      context: .
      dockerfile: Dockerfile
    image: grpcscanner:server
    environment:
      - TZ=Europe/Paris
      - MODE=server
      - DB_DRIVER=redis
      - DB_SERVER=redis:6379
      - DB_PASSWORD=oatiChahNoat6aeliepheijo
      - RMQ_DB_SERVER=redis:6379
      - RMQ_DB_PASSWORD=oatiChahNoat6aeliepheijo
      - RMQ_DB_NAME=scanner
    command: "-server"
    cap_add:
      - NET_ADMIN
    restart: always
    depends_on:
      - redis
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - backend

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: grpcscanner:worker
    environment:
      - TZ="Europe/Paris"
      - CONTROLLER_SERVER=server:9000
      - MODE=worker
      - DB_DRIVER=redis
      - DB_PASSWORD=oatiChahNoat6aeliepheijo
      - DB_SERVER=redis:6379
      - RMQ_DB_SERVER=redis:6379
      - RMQ_DB_NAME=scanner
      - RMQ_DB_PASSWORD=oatiChahNoat6aeliepheijo
      - RMQ_CONSUMERS=10
    command: "-worker"
    restart: always
    cap_add:
      - NET_ADMIN
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: "bitnami/redis:latest"
    environment:
      # - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=oatiChahNoat6aeliepheijo
    restart: always
    volumes:
      - "redis_data:/bitnami/redis/data"
    networks:
      - backend
