version: "3.7"

networks:
  backend:
    external:
      name: my-network

volumes:
  redis_data:
    driver: local

services:
  server:
    hostname: server
    build:
      context: .
      dockerfile: Dockerfile
    image: grpcscanner
    env_file:
      - .envrc
    command: "-server"
    cap_add:
      - NET_ADMIN
    restart: always
    depends_on:
      - redis
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - backend

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: grpcscanner
    env_file:
      - .envrc
    command: "-worker"
    restart: always
    cap_add:
      - NET_ADMIN
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: "bitnami/redis:latest"
    env_file:
      - .envrc
    restart: always
    volumes:
      - "redis_data:/bitnami/redis/data"
    networks:
      - backend
