version: "3.7"

networks:
  backend:
    external:
      name: my-network

volumes:
  redis_data:
    driver: local
  prometheus_data:
    driver: local

services:
  server:
    hostname: server
    build:
      context: .
      dockerfile: Dockerfile
    image: grpcscanner
    env_file:
      - .env
    command: "-server -prometheus -pprof"
    cap_add:
      - NET_ADMIN
    restart: always
    depends_on:
      - redis-sentinel
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
      - "127.0.0.1:6060:6060"
      - "127.0.0.1:2112:2112"
    volumes:
      - "./cert:/etc/scanner/cert:ro"
    networks:
      - backend

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: grpcscanner
    env_file:
      - .env
    command: "-worker -pprof"
    restart: always
    cap_add:
      - NET_ADMIN
    depends_on:
      - redis-sentinel
      - tor
    networks:
      - backend
    ports:
      - "127.0.0.1:16060-16064:6060"
    volumes:
      - "./cert:/etc/scanner/cert:ro"
    deploy:
      mode: replicated
      replicas: 5

  tor:
    image: dperson/torproxy
    restart: always
    networks:
      - backend

  redis-primary:
    image: docker.io/bitnami/redis:6.2
    ports:
      - "6379"
    env_file:
      - .env
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - "redis_data:/bitnami/redis/data"
    restart: always
    networks:
      - backend

  redis-secondary:
    image: docker.io/bitnami/redis:6.2
    ports:
      - "6379"
    depends_on:
      - redis-primary
    env_file:
      - .env
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-primary
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    restart: always
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 5

  redis-sentinel:
    image: "bitnami/redis-sentinel:6.2"
    env_file:
      - .env
    environment:
      - REDIS_MASTER_HOST=redis-primary
    ports:
      - "26379-26381:26379"
    depends_on:
      - redis-primary
      - redis-secondary
    restart: always
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 3

  prometheus:
    image: prom/prometheus:v2.26.0
    env_file:
      - .env
    restart: always
    volumes:
      - ./config/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - "127.0.0.1:9090:9090"
    networks:
      - backend

  # envoy:
  #   image: envoyproxy/envoy-alpine:v1.18-latest
  #   ports:
  #     - "10000:10000"
  #   volumes:
  #     - ./envoy.yaml:/etc/envoy/envoy.yaml
  #   networks:
  #     - backend
