version: "3.7"

networks:
  backend:
    external:
      name: my-network

services:
  client:
    image: namely/grpc-cli
    environment:
      - TZ=Europe/Paris
    networks:
      - backend
    depends_on:
      - server
    command: "grpc_cli ls redis:9000"

  server:
    hostname: server
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    image: grpcscanner:server
    environment:
      - TZ=Europe/Paris
      - REDIS_SERVER=redis:6379
    cap_add:
      - NET_ADMIN
    restart: always
    depends_on:
      - redis
    ports:
      - "9000:9000"
    networks:
      - backend

  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    image: grpcscanner:worker
    environment:
      - TZ=Europe/Paris
      - REDIS_SERVER=redis:6379
    restart: always
    cap_add:
      - NET_ADMIN
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    networks:
      - backend
