apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o kubernetes/
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "9001"
      port: 9001
      targetPort: 9001
    - name: "6060"
      port: 6060
      targetPort: 6060
    - name: "2112"
      port: 2112
      targetPort: 2112
  selector:
    io.kompose.service: server
status:
  loadBalancer: {}
